### ISSUE TITLE
Can cbd_2014_pathway:unaided be improved?

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/alien-birds-checklist#14]
In alien birds checklist, I found that some taxa have pathway information at level 1, some others at level 2:
![image](https://user-images.githubusercontent.com/33662631/79211721-e3a0d400-7e46-11ea-8ee8-b4f6ae5c7959.png)

Taxon Oxyura jamaicensis (Gmelin, 1789) ([159498548](https://www.gbif.org/species/159498548)) has pathway `cbd_2014_pathway:unaided`. Based on what @timadriaens wrote in https://github.com/trias-project/indicators/issues/61#issuecomment-611704751 I wonder whether it is correct or it could be improved as `cbd_2014_pathway:unaided_natural_dispersal`.

**Comment by timadriaens** [comment]
Yes, could be improved. The species, apart from being an escape, does come in from neighbouring countries.

**Comment by sannegovaert** [comment]
I close this issue because it is outdated and not relevant anymore.
