### ISSUE TITLE
Form as taxon rank correct?

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-birds-checklist#3]
`Lonchura striata domestica` has a taxon rank `form` attached to it. Is this correct? 
My feeling is that this should be subspecies.

**Comment by peterdesmet** [comment]
Yes, should be a subspecies: https://en.wikipedia.org/wiki/Society_finch

**Comment by peterdesmet** [comment]
Note that the name is currently the incorrect `Lonchura striata (Linnaeus, 1766)` in #10.
