### ISSUE TITLE
institutionCode and rightsHolder

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-birds-checklist#4]
Which organization can be considered as the rightsholder of the published data?
I'm now using `INBO` for both the `institutionCode` and `rightsHolder` as the publication falls under the TrIAS project, but perhaps we need to change this?

**Comment by timadriaens** [comment]
However, I don't see why you wouldn't use INBO unless the contract with Natagora stipulates otherwise (I don't suppose Natagora would mind either way actually). In any case, for now, it's INBO.

**Comment by peterdesmet** [comment]
Agree with INBO
