### ISSUE TITLE
Native range = southern for Psittacula alexandri (Linnaeus, 1758)

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-birds-checklist#8]
The `native range` of Psittacula alexandri (Linnaeus, 1758)` is currently `southern`.
Could you please complete this record?

**Comment by timadriaens** [comment]
ok, that should be "Southern Asia | southeast Asia". I updated it in the spreadsheet along with some other species for which native range was lacking.

**Comment by timadriaens** [comment]
in fact the native range for birds is so well described that we would be better off feeding this information from another database such as birdlife.

**Comment by peterdesmet** [comment]
Can this issue be closed?

**Comment by timadriaens** [comment]
yes
