### ISSUE TITLE
Separate records for different localities

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-birds-checklist#9]
To integrate different localities for one species, I found two approaches in the dataset:

1. Two different lines, one line per location (e.g. for _Oxyura jamaicensis_)
2. One line for two loations (e.g. _Poicephalus senegalus_), with localities separated by a comma

The specifications in the legend say that only one value for location information is allowed. I will integrate this accordingly, and make two (or more) different lines with only one piece of location information per species

**Comment by LienReyserhove** [comment]
@timadriaens just to make sure that you read this one. I'm closing this issue now :-)

**Comment by timadriaens** [comment]
@LienReyserhove I think this is indeed the way to go for the location information, else it leads to problems when running indicators at regional level. I actually think the mapping of the Manual of Alien Plants should also be adapted that way.
